Repository emc-mongoose/darzee, pull requests merged in 2018-12, with the labels that each got.

#36 [GUI-37] Add gradle to project
  .gitignore
  .gradle/4.10.2/fileHashes/fileHashes.bin
  .gradle/4.10.2/fileHashes/fileHashes.lock
  .gradle/4.10.2/taskHistory/taskHistory.bin
  .gradle/4.10.2/taskHistory/taskHistory.lock
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  build.gradle
  docker/Dockerfile
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  package-lock.json
Labels: ready for review

#32 request nodes configuration
  src/app/config.ts
  src/app/ip-address.service.ts
  src/app/nodeConfig.ts
  src/app/nodes/nodes.component.css
  src/app/nodes/nodes.component.html
  src/app/nodes/nodes.component.ts
Labels: approved

#40 [GUI-52] Add mongoose ip as an argument to NGINX.
  .env
  docker/Dockerfile
  nginx.conf.template
Labels: enhancement

#39 Deletion only one of same ip items
  .env
  build.gradle
  src/app/ip-address.service.ts
  src/app/ipAddress.ts
  src/app/nodes/nodes.component.html
  src/app/nodes/nodes.component.ts
Labels: ready for review

#38 Add port validation
  src/app/nodes/nodes.component.html
  src/app/nodes/nodes.component.ts
Labels: ready for review

#43 Home page remarks
  src/app/nodes/nodes.component.css
  src/app/nodes/nodes.component.html
Labels: enhancement, ready for review

#41 [GUI-55] Update .gitignore to delete production files.
  .env
  .gitignore
  README.md
  build.gradle
  dist/mongoose-console/3rdpartylicenses.txt
  dist/mongoose-console/assets/icons/folder-open-icon.svg
  dist/mongoose-console/assets/icons/icon-navigate-next.svg
  dist/mongoose-console/assets/icons/icon-navigate-previous.svg
  dist/mongoose-console/assets/icons/icon-refresh.svg
  dist/mongoose-console/assets/icons/save-icon.svg
  dist/mongoose-console/assets/images/mongoose.png
  dist/mongoose-console/favicon.ico
  dist/mongoose-console/index.html
  dist/mongoose-console/main.02b3626ffb380a31892b.js
  dist/mongoose-console/polyfills.f6ae3e8b63939c618130.js
  dist/mongoose-console/runtime.ec2944dd8b20ec099bf3.js
  dist/mongoose-console/styles.027568436c0adaf34b4c.css
  docker/Dockerfile
  nginx/nginx.conf.template
Labels: refactor

#45 Gui 48 fix grafana integration
  docker-compose.yml
  grafana_plugins/grafana-graph-panel/LICENSE
  grafana_plugins/grafana-graph-panel/README.md
  grafana_plugins/grafana-graph-panel/package-lock.json
  grafana_plugins/grafana-graph-panel/package.json
  grafana_plugins/grafana-graph-panel/src/axes_editor.ts
  grafana_plugins/grafana-graph-panel/src/data_processor.ts
  grafana_plugins/grafana-graph-panel/src/graph.ts
  grafana_plugins/grafana-graph-panel/src/graph_tooltip.d.ts
  grafana_plugins/grafana-graph-panel/src/graph_tooltip.js
  grafana_plugins/grafana-graph-panel/src/histogram.ts
  grafana_plugins/grafana-graph-panel/src/img/icn-graph-panel.svg
  grafana_plugins/grafana-graph-panel/src/legend.ts
  grafana_plugins/grafana-graph-panel/src/module.ts
  grafana_plugins/grafana-graph-panel/src/partials/axes_editor.html
  grafana_plugins/grafana-graph-panel/src/partials/tab_display.html
  grafana_plugins/grafana-graph-panel/src/partials/tab_legend.html
  grafana_plugins/grafana-graph-panel/src/plugin.json
  grafana_plugins/grafana-graph-panel/src/series_overrides_ctrl.ts
  grafana_plugins/grafana-graph-panel/src/template.ts
  grafana_plugins/grafana-graph-panel/src/threshold_manager.ts
  grafana_plugins/grafana-graph-panel/src/thresholds_form.ts
  grafana_plugins/grafana-graph-panel/src/vendor/flot/jquery.flot.events.js
  grafana_plugins/grafana-graph-panel/src/vendor/grafana/colors.ts
  grafana_plugins/grafana-graph-panel/src/vendor/grafana/event.ts
  grafana_plugins/grafana-graph-panel/src/vendor/grafana/event_manager.ts
  grafana_plugins/grafana-graph-panel/src/vendor/grafana/ticks.ts
  grafana_plugins/grafana-graph-panel/src/vendor/grafana/time_series2.ts
  grafana_plugins/grafana-graph-panel/tsconfig.json
  src/main/grafana/plugins/grafana-graph-panel/.gitignore
Labels: bug fix, ready for review
